name: Auto Bump Version

on:
  pull_request:
    types: [closed]
    branches: [main]

  workflow_dispatch:

jobs:
  bump-version:
    name: Bump version and create changelog with commitizen
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true && (
        contains(github.event.pull_request.labels.*.name, 'release') ||
        contains(github.event.pull_request.labels.*.name, 'Release')
      ))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Configure Git User
        run: |
          git config user.name "Sahil Anguralla"
          git config user.email "anguralla.sahil@gmail.com"

      - name: Bump version
        id: cz_bump
        run: |
          # Perform the bump on main
          if cz bump --yes; then
            echo "bumped=true" >> $GITHUB_OUTPUT
            git push origin main --tags
          else
            echo "bumped=false" >> $GITHUB_OUTPUT
          fi
