name: Auto Bump Version

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
    branches: [main]

  workflow_dispatch:

jobs:
  bump-version:
    name: Bump version and create changelog with commitizen
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Configure Git User
        run: |
          git config user.name "Raven"
          git config user.email "raven[bot]@users.noreply.github.com"

      - name: Bump version
        id: cz_bump
        run: |
          # Perform the bump on PR branch updating files only
          if cz bump --yes --version-files-only; then
            # Get the new version using python to read it from manifest.json
            NEW_VERSION=$(python3 -c "import json; print(json.load(open('custom_components/amtrak_tracker/manifest.json'))['version'])")
            
            # Commit the changed version files
            git add custom_components/amtrak_tracker/manifest.json pyproject.toml
            git commit -m "bump: version to $NEW_VERSION"
            
            echo "bumped=true" >> $GITHUB_OUTPUT
            git push origin HEAD:${{ github.event.pull_request.head.ref }} || echo "Failed to push version bump."
          else
            echo "bumped=false" >> $GITHUB_OUTPUT
          fi
