name: Auto Bump Version

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
    branches: [main]

  workflow_dispatch:

jobs:
  bump-version:
    name: Bump version and create changelog with commitizen
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Configure Git User
        run: |
          git config user.name "Raven"
          git config user.email "raven[bot]@users.noreply.github.com"

      - name: Bump version
        id: cz_bump
        run: |
          # Perform the bump on PR branch
          if cz bump --yes --no-tag; then
            echo "bumped=true" >> $GITHUB_OUTPUT
            git push origin HEAD:${{ github.event.pull_request.head.ref }} || echo "Failed to push version bump."
          else
            echo "bumped=false" >> $GITHUB_OUTPUT
          fi
